PROC IML;
    TITLE "Algoritmo de Aceptación-Rechazo";
    n = 1000000;
    c = 1.5;
    START aar(n) GLOBAL(c);
        x = J(n,1);
        i = 0;
        j = 0;
        DO WHILE (i < n);
            y = J(1,1);
            CALL RANDGEN(y,"CAUCHY");
            gy = PDF("CAUCHY",y);
            fy = PDF("NORMAL",y);
            u = J(1,1);
            CALL RANDGEN(u,"UNIFORM");
            IF (u < fy/(c#gy)) THEN DO;
                i = i +1;
                x[i] = y;
            END;
            j = j + 1;
        END;
        MATTRIB j LABEL = "Número de iteraciones";
        PRINT j;
        RETURN(x);
    FINISH;
    x = aar(n);
    CREATE datos FROM x[COLNAME = {"X"}];
    APPEND FROM x;
QUIT;
PROC SGPLOT DATA = datos;
    HISTOGRAM x;
    DENSITY x;
QUIT;