PROC IML;
	TITLE "Polar method";
    n = 1000000;
    START polar(n);
        x = J(n,1);
        y = J(n,1);
        i = 0;
        j = 0;
        DO WHILE (i < n);
            u1 = J(1,1);
            u2 = J(1,1);
            CALL RANDGEN(u1,"UNIFORM");
            CALL RANDGEN(u2,"UNIFORM");
			v1 = 2#u1-1;
			v2 = 2#u2-1;
            s = v1##2 + v2##2;
            IF (s < 1) THEN DO;
                i = i+1;
                x[i] = SQRT((-2#LOG(s))/s)#v1;
                y[i] = SQRT((-2#LOG(s))/s)#v2;
            END;
            j = j+1;
        END;
        xy = (x + y)/SQRT(2);
        MATTRIB j LABEL = "Number of iterations";
        PRINT j;
        RETURN(xy);
    FINISH;
    z = polar(n);
    CREATE datos FROM z[COLNAME = {"Z"}];
    APPEND FROM z;
QUIT;
PROC SGPLOT DATA = datos;
    HISTOGRAM z;
    DENSITY z;
RUN;
